spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:default-access-key}
      secret-key: ${AWS_SECRET_KEY:default-secret-key}
    s3:
      bucket: ${S3_BUCKET_NAME:ieumai-s3-bucket}
      enabled: true
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

# AWS SES 관련 설정
aws:
  ses:
    from-email: ${SES_FROM_EMAIL:noreply@example.com}
    enabled: true

# JWT 관련 설정
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

openai:
  api-key: ${OPENAI_API_KEY}