# 일부러 gitignore 안한거임 안에 든게 없음

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC
    username: eeedddiii
    password: 0125
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  ses:
    from: ${SES_FROM_EMAIL}

jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-characters
  token-validity-in-seconds: 86400

file:
  upload:
    path: /path/to/your/upload/directory



  #MYSQL_USER=your_mysql_user
  #MYSQL_PASSWORD=your_mysql_password
  #AWS_ACCESS_KEY=your_aws_access_key
  #AWS_SECRET_KEY=your_aws_secret_key
  #AWS_REGION=your_aws_region
  #SES_FROM_EMAIL=your_verified_sender@domain.com
  #JWT_SECRET=your_jwt_secret