spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

# AWS SES 관련 설정
aws:
  ses:
    from: ${SES_FROM_EMAIL}

# JWT 관련 설정
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

openai:
  api-key: ${OPENAI_API_KEY}