# .github/workflows/deploy.yml

name: Deploy to EC2 on main push

on:
  push:
    branches:
      - main # main 브랜치에 push 이벤트가 발생했을 때 실행됩니다.

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest # 워크플로우를 실행할 환경

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2 instance via SSH
      uses: appleboy/ssh-action@master # SSH 연결 및 명령어 실행을 위한 액션
      with:
        host: ${{ secrets.EC2_HOST_IP }}        # GitHub Secrets에서 호스트 IP 가져오기
        username: ${{ secrets.EC2_USERNAME }}     # GitHub Secrets에서 사용자 이름 가져오기
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # GitHub Secrets에서 PEM 키 내용 가져오기
        port: 22             # SSH 포트 (기본값은 22, 필요시 secret으로 관리 가능)
        script: | # EC2 인스턴스에서 실행할 명령어들
          echo "Attempting to send command to screen session 'ieumai-backend'..."
          screen -S ieumai-backend -X stuff "sudo sh ~/ieumai-backend/build-script.sh\n"
          echo "Command sent to screen session 'ieumai-backend'."
