name: Deploy to EC2 on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Run build-script.sh on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/ieumai-backend
          bash build-script.sh
