# .github/workflows/deploy.yml

name: Deploy to EC2 on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Manage Screen Session and Run Build Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          WORK_DIR="/home/ec2-user/ieumai-backend" # 작업 디렉토리 변수
          SCRIPT_NAME="build-script.sh"          # 스크립트 이름 변수 (WORK_DIR 내부에 있다고 가정)
          SESSION_NAME="ieumai-backend"

          # 1. 기존 세션 확인 및 종료
          echo "Checking for existing screen session: $SESSION_NAME"
          if screen -ls | grep -q "\.$SESSION_NAME\s"; then
            echo "Existing session found. Terminating..."
            screen -S $SESSION_NAME -X quit
            sleep 1
            echo "Existing session terminated."
          else
            echo "No existing session found."
          fi

          # 2. 새 세션 생성
          echo "Creating new detached screen session: $SESSION_NAME"
          screen -S $SESSION_NAME -d -m

          # 3. 새 세션에 디렉토리 이동 및 빌드 스크립트 실행 명령어 전송
          # '&&'를 사용하여 cd 명령이 성공했을 때만 다음 명령어를 실행합니다.
          COMMAND_TO_RUN="cd $WORK_DIR && sudo sh $SCRIPT_NAME"
          echo "Sending commands to new session: $COMMAND_TO_RUN"

          # 'stuff' 명령어는 문자열을 순차적으로 입력합니다.
          screen -S $SESSION_NAME -X stuff "$COMMAND_TO_RUN$(printf '\r')" # 명령어 + Enter 키 입력 효과

          echo "Commands sent successfully to $SESSION_NAME."
